name: Build image

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**.yml"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install deps
        run: sudo apt-get install -yq build-essential automake autoconf pkg-config cmake libssl-dev git git-lfs

      - run: corepack enable
      - run: yarn set version stable
      - run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install

      - name: Build
        run: make dist

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: pankaj19soni
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: pankaj19soni/listmonk:5.20, pankaj19soni/listmonk:latest
